### ISSUE TITLE
Branching Naming

### ISSUE THREAD

**Issue by fatihtatoglu** [anatoliansoftwarecommunity/welcome#10]
As we discussed;
- Every repositories will have `master` branch.
- When new branch is required, branch name will be same with issue key.

**Comment by fatihtatoglu** [comment]
In addition after thinking, should we need project abbreviations. If we have project abbreviations we can separate projects logically.

**Comment by onurmenal** [comment]
> My open topic is how will we deal with hotfixes or feature developments? I guess we need to decide a git strategy for branching & merging.
> 
> What do you think? @onurmenal

Lets discuss that before decide.

**Comment by fatihtatoglu** [comment]
We will continue with the issue number for branch names until we discuss it. We will also test whether it works or not.
