### ISSUE TITLE
Issue and Pull Request linking

### ISSUE THREAD

**Issue by fatihtatoglu** [anatoliansoftwarecommunity/welcome#12]
As we discussed;

- Every pull request must be linked with an issue. 

I found [Linking a pull request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) article. As I read, using keyword is working only default branch. However we will link every pull request and issues.

@onurmenal do you have any opinion?

**Comment by onurmenal** [comment]
I think default approach is clear. We didn't discuss code review standarts yet. May be we can check all of this details on code review stage.
