### ISSUE TITLE
Coding Standards

### ISSUE THREAD

**Issue by fatihtatoglu** [anatoliansoftwarecommunity/welcome#14]
As we talked, we must have a coding standard and also it will be incremental.

First of all, we will start development with C#. Am I right @onurmenal ?

**Comment by onurmenal** [comment]
Right, that's what we decided.

**Comment by fatihtatoglu** [comment]
I guess we need to arrange a short meeting about this. @onurmenal what do you think?

**Comment by fatihtatoglu** [comment]
After the last meeting that was made on 9th November 2021, we have decided on some code standards for the C# language.
