### ISSUE TITLE
Define simple standard

### ISSUE THREAD

**Issue by fatihtatoglu** [anatoliansoftwarecommunity/welcome#4]
Need to decide on the following issues.

- [x] #5
- [x] #7
- [x] #8
- [x] #6
- [x] #9
- [x] #10
- [x] #17
- [x] #12
- [x] #14
- [x] #11
- [x] #13

**Comment by fatihtatoglu** [comment]
After completing above items, we will be ready for development. @onurmenal I need your help for completing items. 🆘

**Comment by onurmenal** [comment]
> After completing above items, we will be ready for development. @onurmenal I need your help for completing items. 🆘

I complete my review for above list.

**Comment by fatihtatoglu** [comment]
All of the items were completed. We are ready for developing the project.
