### ISSUE TITLE
Labels and descriptions

### ISSUE THREAD

**Issue by fatihtatoglu** [anatoliansoftwarecommunity/welcome#5]
While searching I found https://github.com/abdonrd/github-labels and I create a list of the labels in below.

| Group | Name | Color Code | Key | Description |
|:-------|:------|------------|:-----|:-------------|
| Priority | Blocker | `#b60205` | priority: blocker | |
| Priority | Critical | `#d93f0b` | priority: critical | |
| Priority | High | `#fbca04` | priority: high | |
| Priority | Medium | `#0e8a16` | priority: medium | |
| Priority | Low | `#1e90ff` | priority: low | |
| | | | | |
| Status | Triage | `#d4c5f9`| status: triage | This issue needs to analyze |
| Status | Can't reproduce | `#fec1c1`| status: can't reproduce | This issue can't reproduce |
| Status | Confirmed | `#215cea`| status: confirmed | This issue is confirmed |
| Status | Duplicate | `#cfd3d7`| status: duplicate | This issue or pull request already exists |
| Status | Needs information | `#fef2c0`| status: needs information | This issue needs additional information |
| Status | Won't do/fix | `#eeeeee`| status: wont do/fix | This issue won't do/fix |
| | | | | |
| Type | Bug | `#d73a4a` | type: bug | Something isn't working |
| Type | New Feature | `#fbca04` | type: new feature | New feature |
| Type | Documentation | `#006b75` | type: documentation | Improvements or additions to documentation |
| Type | Enhancement | `#84b6eb` | type: enhancement | This issue improve quality/efficiency |
| Type | Epic | `#3e4b9e` | type: epic | This issue needs to split into sub-tasks |
| | | | | |
| Global | Discussion | `#d876e3` | discussion | |

**Comment by onurmenal** [comment]
The above list is very clear for me. We can keep it like that.

**Comment by fatihtatoglu** [comment]
Current repository and organization repository defaults updated.
