### ISSUE TITLE
Documentation type and path

### ISSUE THREAD

**Issue by fatihtatoglu** [anatoliansoftwarecommunity/welcome#6]
For documentation we decided below topics.

- Documentation will be in MarkDown format.
- Every repository will have `docs` folder.
- [Welcome](https://github.com/anatoliansoftwarecommunity/welcome) repository will keep global documentation.

**Comment by fatihtatoglu** [comment]
For documentation we decided below topics.

- Documentation will be in MarkDown format.
- Every repository will have `docs` folder.
- [Welcome](https://github.com/anatoliansoftwarecommunity/welcome) repository will keep global documentation.

**Comment by onurmenal** [comment]
> @onurmenal One open topic for me, will documentation be multi language (i.e. Turkish & English)?
> 
> In my opinion multiple language will be good for reaching a lot of contributors, members, and users.

I think English is good for start.

**Comment by fatihtatoglu** [comment]
> For global documentation (i.e. standards, decisions etc.) I cannot find a correct word. My alternatives are; **rules** and **standard**. But after reading following link I am confused again. 😕
> 
> https://lsolum.typepad.com/legaltheory/2009/09/legal-theory-lexicon-rules-standards-and-principles.html
> 
> Which do you prefer? Please keep in mind future working style and people get used to these topics after joining into community.

@onurmenal what do you think about this ?

**Comment by onurmenal** [comment]
My vote goes to "standard"  👌

**Comment by fatihtatoglu** [comment]
Ok we will continue with **standard**.
